### ISSUE TITLE
npm WARN deprecated nomnom@1.8.1

### ISSUE THREAD

**Issue by creage** [mikeedwards/po2json#81]
### Expected Behavior
Install with no issues

### Actual Behavior
NPM warning during installation

### Steps to Reproduce
npm i

**Comment by mikeedwards** [comment]
fixed

**Comment by Pyrolistical** [comment]
will be fixed once 1.0.0 is released. still a problem on latest npm version of 0.4.5
